"""add personal_org_id to users, org_id to projects, persona to project_members

Revision ID: 0d085200a7a5
Revises: 001_org_tables
Create Date: 2026-02-27 01:13:03.760584
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0d085200a7a5'
down_revision: Union[str, None] = '001_org_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('persona', sa.Enum('developer', 'creator', 'operations', 'finance', name='projectpersona'), nullable=False, server_default='creator'))
    op.add_column('projects', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'organizations', ['org_id'], ['id'])
    op.add_column('users', sa.Column('personal_org_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['personal_org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'personal_org_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'org_id')
    op.drop_column('project_members', 'persona')
    # ### end Alembic commands ###
